In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
interactions = pd.read_csv(
    "learntwin_student_interactions.csv"
)

questions = pd.read_csv(
    "learntwin_questions.csv"
)

print("Interactions shape:", interactions.shape)
print("Questions shape:", questions.shape)

print("\nInteraction columns:")
print(interactions.columns.tolist())

print("\nQuestion columns:")
print(questions.columns.tolist())

Interactions shape: (10000, 10)
Questions shape: (500, 3)

Interaction columns:
['student_id', 'attempt', 'question_id', 'concept', 'difficulty', 'correct', 'time_gap_days', 'days_since_practice', 'timestamp', 'knowledge_state']

Question columns:
['question_id', 'concept', 'difficulty']

## Understand the datasets

In [4]:
interactions.head()

,student_id,attempt,question_id,concept,difficulty,correct,time_gap_days,days_since_practice,timestamp,knowledge_state
0,S001,1,Q043,RIGHT JOIN,0.724,0,3.007,3.007,3.007,0.3574
1,S001,2,Q452,RIGHT JOIN,0.577,0,1.471,1.471,4.478,0.3103
2,S001,3,Q022,UNION,0.499,1,1.675,6.154,6.154,0.3849
3,S001,4,Q007,WHERE,0.380,1,0.563,6.717,6.717,0.4015
4,S001,5,Q114,STORED PROCEDURES,0.598,1,2.683,9.400,9.400,0.1345

In [5]:
questions.head()

  question_id              concept  difficulty
0        Q001           INNER JOIN       0.589
1        Q002        NORMALIZATION       0.720
2        Q003           INNER JOIN       0.484
3        Q004  AGGREGATE FUNCTIONS       0.438
4        Q005             GROUP BY       0.393

In [6]:
questions.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   question_id  500 non-null    str
 1   concept      500 non-null    str
 2   difficulty   500 non-null    float64
dtypes: float64(1), str(2)
memory usage: 11.8 KB

In [7]:
questions.describe(include="all")

       question_id concept  difficulty
count          500     500  500.000000
unique         500      20         NaN
top           Q001  HAVING         NaN
freq             1      33         NaN
mean           NaN     NaN    0.503694
std            NaN     NaN    0.158843
min            NaN     NaN    0.152000
25%            NaN     NaN    0.386500
50%            NaN     NaN    0.504000
75%            NaN     NaN    0.633000
max            NaN     NaN    0.846000

In [8]:
questions["concept"].value_counts()

concept
HAVING                 33
SELECT                 32
WHERE                  31
VIEWS                  30
NORMALIZATION          29
ORDER BY               28
JOINS                  27
LEFT JOIN              27
AGGREGATE FUNCTIONS    25
TRIGGERS               25
GROUP BY               24
RIGHT JOIN             24
INNER JOIN             23
INDEXING               23
FOREIGN KEY            23
PRIMARY KEY            22
SUBQUERIES             21
STORED PROCEDURES      20
TRANSACTIONS           17
UNION                  16
Name: count, dtype: int64

In [9]:
print(
    questions["difficulty"].value_counts()
    .sort_index()
)

difficulty
0.152    1
0.153    1
0.156    1
0.158    1
0.171    1
        ..
0.818    1
0.827    1
0.828    1
0.835    1
0.846    1
Name: count, Length: 346, dtype: int64

## 5.6 — Calculate student concept performance

In [10]:
interactions["timestamp"] = pd.to_datetime(
    interactions["timestamp"]
)

interactions = interactions.sort_values(
    by=["student_id", "timestamp"]
).reset_index(drop=True)

In [11]:
concept_performance = (
    interactions
    .groupby(["student_id", "concept"])
    .agg(
        attempts=("correct", "count"),
        correct_answers=("correct", "sum"),
        accuracy=("correct", "mean"),
        average_gap=("days_since_practice", "mean")
    )
    .reset_index()
)

In [12]:
concept_performance.head(20)

,student_id,concept,attempts,correct_answers,accuracy,average_gap
0,S001,AGGREGATE FUNCTIONS,5,2,0.400000,27.441000
1,S001,FOREIGN KEY,4,1,0.250000,33.362750
2,S001,GROUP BY,5,1,0.200000,20.066600
3,S001,HAVING,3,0,0.000000,39.919000
4,S001,INDEXING,4,1,0.250000,35.362250
5,S001,INNER JOIN,6,1,0.166667,20.996333
6,S001,JOINS,4,0,0.000000,34.170500
7,S001,LEFT JOIN,3,0,0.000000,25.233000
8,S001,NORMALIZATION,4,2,0.500000,29.038000
9,S001,ORDER BY,4,4,1.000000,32.755250
10,S001,PRIMARY KEY,7,4,0.571429,19.906714
11,S001,RIGHT JOIN,7,0,0.000000,17.175857
12,S001,SELECT,7,2,0.285714,18.343286
13,S001,STORED PROCEDURES,4,2,0.500000,28.928000
14,S001,SUBQUERIES,4,1,0.250000,24.486250
15,S001,TRANSACTIONS,2,0,0.000000,71.618500
16,S001,TRIGGERS,6,0,0.000000,22.808167
17,S001,UNION,3,2,0.666667,27.773333
18,S001,VIEWS,8,1,0.125000,16.615500
19,S001,WHERE,10,5,0.500000,12.661300

## 5.7 — Identify weak concepts

In [13]:
weak_concepts = concept_performance[
    concept_performance["accuracy"] < 0.60
].copy()

print("Number of weak concept records:",
      len(weak_concepts))

weak_concepts.head(20)

Number of weak concept records: 1732

,student_id,concept,attempts,correct_answers,accuracy,average_gap
0,S001,AGGREGATE FUNCTIONS,5,2,0.400000,27.441000
1,S001,FOREIGN KEY,4,1,0.250000,33.362750
2,S001,GROUP BY,5,1,0.200000,20.066600
3,S001,HAVING,3,0,0.000000,39.919000
4,S001,INDEXING,4,1,0.250000,35.362250
5,S001,INNER JOIN,6,1,0.166667,20.996333
6,S001,JOINS,4,0,0.000000,34.170500
7,S001,LEFT JOIN,3,0,0.000000,25.233000
8,S001,NORMALIZATION,4,2,0.500000,29.038000
10,S001,PRIMARY KEY,7,4,0.571429,19.906714
11,S001,RIGHT JOIN,7,0,0.000000,17.175857
12,S001,SELECT,7,2,0.285714,18.343286
13,S001,STORED PROCEDURES,4,2,0.500000,28.928000
14,S001,SUBQUERIES,4,1,0.250000,24.486250
15,S001,TRANSACTIONS,2,0,0.000000,71.618500
16,S001,TRIGGERS,6,0,0.000000,22.808167
18,S001,VIEWS,8,1,0.125000,16.615500
19,S001,WHERE,10,5,0.500000,12.661300
20,S002,AGGREGATE FUNCTIONS,2,1,0.500000,53.478500
21,S002,FOREIGN KEY,4,2,0.500000,32.346750

## 5.8 — Load the forgetting model

In [14]:
import joblib

forgetting_model = joblib.load(
    "learntwin_forgetting_model.pkl"
)

print("Forgetting model loaded successfully!")

Forgetting model loaded successfully!

## 5.9 — Calculate forgetting risk for the student's concepts

In [15]:
concept_group = interactions.groupby(
    ["student_id", "concept"]
)

interactions["concept_prior_correct"] = (
    concept_group["correct"].cumsum()
    - interactions["correct"]
)

interactions["concept_prior_attempts"] = (
    concept_group.cumcount()
)

interactions["concept_prior_accuracy"] = np.where(
    interactions["concept_prior_attempts"] > 0,
    interactions["concept_prior_correct"] /
    interactions["concept_prior_attempts"],
    0.5
)

In [16]:
interactions["student_prior_correct"] = (
    interactions
    .groupby("student_id")["correct"]
    .cumsum()
    - interactions["correct"]
)

interactions["student_prior_attempts"] = (
    interactions.groupby("student_id").cumcount()
)

interactions["student_prior_accuracy"] = np.where(
    interactions["student_prior_attempts"] > 0,
    interactions["student_prior_correct"] /
    interactions["student_prior_attempts"],
    0.5
)

## 5.10 — Generate forgetting probabilities

In [17]:
forgetting_features = [
    "concept",
    "difficulty",
    "time_gap_days",
    "days_since_practice",
    "student_prior_attempts",
    "student_prior_accuracy",
    "concept_prior_attempts",
    "concept_prior_accuracy"
]

In [18]:
latest_concept_state = (
    interactions
    .sort_values("timestamp")
    .groupby(["student_id", "concept"])
    .tail(1)
    .copy()
)

In [19]:
latest_concept_state["forgetting_probability"] = (
    forgetting_model.predict_proba(
        latest_concept_state[forgetting_features]
    )[:, 1]
)

In [20]:
latest_concept_state[
    [
        "student_id",
        "concept",
        "correct",
        "concept_prior_accuracy",
        "days_since_practice",
        "forgetting_probability"
    ]
].head(20)

,student_id,concept,correct,concept_prior_accuracy,days_since_practice,forgetting_probability
7002,S071,SUBQUERIES,0,0.5,1.325,0.451983
6703,S068,TRANSACTIONS,0,0.5,4.061,0.380751
2104,S022,TRANSACTIONS,1,0.5,4.087,0.337902
8805,S089,UNION,0,0.5,10.022,0.312093
2607,S027,TRANSACTIONS,0,0.5,10.035,0.342842
511,S006,SELECT,0,0.5,11.937,0.343080
4611,S047,ORDER BY,1,0.5,12.938,0.370795
906,S010,UNION,0,0.0,10.360,0.364847
9514,S096,RIGHT JOIN,0,0.0,8.486,0.325394
7713,S078,UNION,1,0.5,20.135,0.366618
6415,S065,GROUP BY,0,0.5,20.251,0.538272
9909,S100,ORDER BY,0,0.5,23.213,0.491543
9222,S093,TRANSACTIONS,1,0.5,1.050,0.320613
8220,S083,LEFT JOIN,1,0.5,12.502,0.346947
2314,S024,INDEXING,0,0.5,8.963,0.435546
6229,S063,TRANSACTIONS,0,0.5,27.339,0.533929
8625,S087,UNION,0,0.5,29.900,0.602723
5126,S052,STORED PROCEDURES,1,0.0,27.257,0.594407
7919,S080,GROUP BY,0,0.0,10.066,0.413056
2626,S027,GROUP BY,0,0.0,1.837,0.289824

## 5.11 — Create a combined student-concept profile

In [21]:
student_concept_profile = concept_performance.merge(
    latest_concept_state[
        [
            "student_id",
            "concept",
            "days_since_practice",
            "forgetting_probability"
        ]
    ],
    on=["student_id", "concept"],
    how="left"
)

In [22]:
student_concept_profile.head(20)

,student_id,concept,attempts,correct_answers,accuracy,average_gap,days_since_practice,forgetting_probability
0,S001,AGGREGATE FUNCTIONS,5,2,0.400000,27.441000,7.027,0.336455
1,S001,FOREIGN KEY,4,1,0.250000,33.362750,10.409,0.438448
2,S001,GROUP BY,5,1,0.200000,20.066600,7.313,0.369125
3,S001,HAVING,3,0,0.000000,39.919000,29.845,0.603047
4,S001,INDEXING,4,1,0.250000,35.362250,3.540,0.466624
5,S001,INNER JOIN,6,1,0.166667,20.996333,6.815,0.469696
6,S001,JOINS,4,0,0.000000,34.170500,21.402,0.615172
7,S001,LEFT JOIN,3,0,0.000000,25.233000,38.887,0.603387
8,S001,NORMALIZATION,4,2,0.500000,29.038000,10.140,0.449495
9,S001,ORDER BY,4,4,1.000000,32.755250,37.258,0.636377
10,S001,PRIMARY KEY,7,4,0.571429,19.906714,2.050,0.327731
11,S001,RIGHT JOIN,7,0,0.000000,17.175857,47.727,0.675587
12,S001,SELECT,7,2,0.285714,18.343286,23.441,0.509396
13,S001,STORED PROCEDURES,4,2,0.500000,28.928000,16.195,0.474253
14,S001,SUBQUERIES,4,1,0.250000,24.486250,19.715,0.615356
15,S001,TRANSACTIONS,2,0,0.000000,71.618500,104.227,0.965752
16,S001,TRIGGERS,6,0,0.000000,22.808167,3.368,0.413637
17,S001,UNION,3,2,0.666667,27.773333,53.190,0.731926
18,S001,VIEWS,8,1,0.125000,16.615500,20.102,0.495996
19,S001,WHERE,10,5,0.500000,12.661300,20.863,0.448921

## Student
 ##  ↓
## Concept
 ##  ↓
## Accuracy
   ## +
## Time since practice
  ## +
## Forgetting probability

## 5.12 — Create a priority score

Weakness
+
Forgetting risk

In [23]:
student_concept_profile["weakness_score"] = (
    1 - student_concept_profile["accuracy"]
)

In [24]:
student_concept_profile["priority_score"] = (
    0.6 *
    student_concept_profile["weakness_score"]
    +
    0.4 *
    student_concept_profile["forgetting_probability"]
)

## 60% → current weakness
## 40% → forgetting risk

## 5.13 — See the highest-priority concepts

In [25]:
student_concept_profile = (
    student_concept_profile
    .sort_values(
        "priority_score",
        ascending=False
    )
)

student_concept_profile.head(20)

,student_id,concept,attempts,correct_answers,accuracy,average_gap,days_since_practice,forgetting_probability,weakness_score,priority_score
905,S046,SUBQUERIES,1,0,0.0,147.500000,147.500,0.993690,1.0,0.997476
1516,S077,TRANSACTIONS,1,0,0.0,146.438000,146.438,0.992034,1.0,0.996814
927,S047,UNION,1,0,0.0,156.194000,156.194,0.991567,1.0,0.996627
290,S015,RIGHT JOIN,1,0,0.0,156.214000,156.214,0.990711,1.0,0.996284
1004,S051,TRIGGERS,4,0,0.0,38.973250,138.198,0.990522,1.0,0.996209
1496,S076,TRANSACTIONS,1,0,0.0,140.344000,140.344,0.989815,1.0,0.995926
1303,S067,AGGREGATE FUNCTIONS,2,0,0.0,76.138500,144.740,0.988554,1.0,0.995422
1259,S064,SUBQUERIES,2,0,0.0,73.387000,122.134,0.988233,1.0,0.995293
1777,S090,VIEWS,2,0,0.0,86.201500,143.974,0.987771,1.0,0.995108
1794,S091,TRANSACTIONS,1,0,0.0,133.016000,133.016,0.987552,1.0,0.995021
1799,S092,AGGREGATE FUNCTIONS,1,0,0.0,145.006000,145.006,0.986022,1.0,0.994409
1681,S086,FOREIGN KEY,2,0,0.0,79.876000,134.951,0.985834,1.0,0.994334
1202,S061,UNION,1,0,0.0,129.829000,129.829,0.983675,1.0,0.993470
1554,S079,STORED PROCEDURES,2,0,0.0,70.922000,127.549,0.981633,1.0,0.992653
562,S029,LEFT JOIN,1,0,0.0,129.820000,129.820,0.980925,1.0,0.992370
86,S005,JOINS,1,0,0.0,126.006000,126.006,0.979942,1.0,0.991977
1832,S093,SUBQUERIES,3,0,0.0,44.451667,115.649,0.976127,1.0,0.990451
1664,S085,INDEXING,1,0,0.0,116.782000,116.782,0.975503,1.0,0.990201
1402,S072,AGGREGATE FUNCTIONS,1,0,0.0,130.334000,130.334,0.971573,1.0,0.988629
85,S005,INNER JOIN,2,0,0.0,54.550000,96.892,0.971456,1.0,0.988582

## 5.14 — Select questions for the weak concept

In [26]:
student_id = "S001"

In [27]:
def recommend_questions(
    student_id,
    num_questions=5
):
    
    # Get this student's concept profile
    student_profile = student_concept_profile[
        student_concept_profile["student_id"] == student_id
    ].copy()
    
    if student_profile.empty:
        print("Student not found.")
        return pd.DataFrame()
    
    # Highest priority concept
    target_concept = (
        student_profile
        .sort_values(
            "priority_score",
            ascending=False
        )
        .iloc[0]["concept"]
    )
    
    # Get questions for that concept
    candidate_questions = questions[
        questions["concept"] == target_concept
    ].copy()
    
    # Remove questions already attempted
    attempted_questions = interactions[
        interactions["student_id"] == student_id
    ]["question_id"].unique()
    
    candidate_questions = candidate_questions[
        ~candidate_questions["question_id"]
        .isin(attempted_questions)
    ]
    
    # If no new questions remain
    if candidate_questions.empty:
        print(
            "No unattempted questions available "
            "for this concept."
        )
        return pd.DataFrame()
    
    # Return available questions
    return candidate_questions.head(
        num_questions
    )

## 5.15 — Test the recommender

In [28]:
print(
    interactions["student_id"]
    .unique()[:10]
)

<StringArray>
['S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 'S008', 'S009',
 'S010']
Length: 10, dtype: str

In [29]:
test_student = interactions[
    "student_id"
].iloc[0]

print("Testing student:", test_student)

Testing student: S001

In [30]:
recommended = recommend_questions(
    test_student,
    num_questions=5
)

recommended

    question_id       concept  difficulty
66         Q067  TRANSACTIONS       0.606
93         Q094  TRANSACTIONS       0.694
94         Q095  TRANSACTIONS       0.782
101        Q102  TRANSACTIONS       0.659
110        Q111  TRANSACTIONS       0.674

## Student History
   ##   ↓
## Concept Accuracy
   ##     ↓
## Weakness Score
   ##   ↓
## Forgetting Prediction
   ##   ↓
## Forgetting Probability
   ##   ↓
## Priority Score
   ##   ↓
## Weakest / highest-risk Concept
   ##   ↓
## Find unattempted questions
   ##   ↓
## Recommend questions

In [32]:
print("Question difficulty values:")
print(sorted(questions["difficulty"].unique()))

Question difficulty values:
[np.float64(0.152), np.float64(0.153), np.float64(0.156), np.float64(0.158), np.float64(0.171), np.float64(0.185), np.float64(0.193), np.float64(0.199), np.float64(0.2), np.float64(0.202), np.float64(0.205), np.float64(0.206), np.float64(0.207), np.float64(0.209), np.float64(0.21), np.float64(0.213), np.float64(0.216), np.float64(0.219), np.float64(0.22), np.float64(0.221), np.float64(0.223), np.float64(0.224), np.float64(0.226), np.float64(0.227), np.float64(0.229), np.float64(0.235), np.float64(0.241), np.float64(0.246), np.float64(0.249), np.float64(0.254), np.float64(0.255), np.float64(0.258), np.float64(0.261), np.float64(0.262), np.float64(0.263), np.float64(0.264), np.float64(0.265), np.float64(0.268), np.float64(0.269), np.float64(0.27), np.float64(0.273), np.float64(0.282), np.float64(0.283), np.float64(0.285), np.float64(0.287), np.float64(0.288), np.float64(0.29), np.float64(0.294), np.float64(0.297), np.float64(0.299), np.float64(0.301), np.float64(0.307), np.float64(0.309), np.float64(0.31), np.float64(0.311), np.float64(0.313), np.float64(0.318), np.float64(0.319), np.float64(0.322), np.float64(0.323), np.float64(0.324), np.float64(0.326), np.float64(0.33), np.float64(0.333), np.float64(0.334), np.float64(0.335), np.float64(0.336), np.float64(0.337), np.float64(0.338), np.float64(0.339), np.float64(0.341), np.float64(0.343), np.float64(0.344), np.float64(0.346), np.float64(0.348), np.float64(0.354), np.float64(0.355), np.float64(0.356), np.float64(0.357), np.float64(0.359), np.float64(0.36), np.float64(0.361), np.float64(0.363), np.float64(0.364), np.float64(0.366), np.float64(0.367), np.float64(0.37), np.float64(0.371), np.float64(0.373), np.float64(0.374), np.float64(0.376), np.float64(0.377), np.float64(0.378), np.float64(0.38), np.float64(0.381), np.float64(0.382), np.float64(0.384), np.float64(0.385), np.float64(0.387), np.float64(0.388), np.float64(0.39), np.float64(0.391), np.float64(0.392), np.float64(0.393), np.float64(0.397), np.float64(0.4), np.float64(0.401), np.float64(0.402), np.float64(0.403), np.float64(0.405), np.float64(0.406), np.float64(0.407), np.float64(0.408), np.float64(0.411), np.float64(0.414), np.float64(0.415), np.float64(0.416), np.float64(0.417), np.float64(0.419), np.float64(0.42), np.float64(0.421), np.float64(0.422), np.float64(0.424), np.float64(0.425), np.float64(0.426), np.float64(0.43), np.float64(0.431), np.float64(0.433), np.float64(0.435), np.float64(0.436), np.float64(0.438), np.float64(0.44), np.float64(0.442), np.float64(0.443), np.float64(0.445), np.float64(0.446), np.float64(0.447), np.float64(0.448), np.float64(0.449), np.float64(0.451), np.float64(0.452), np.float64(0.454), np.float64(0.455), np.float64(0.457), np.float64(0.458), np.float64(0.46), np.float64(0.462), np.float64(0.464), np.float64(0.465), np.float64(0.466), np.float64(0.469), np.float64(0.47), np.float64(0.471), np.float64(0.472), np.float64(0.473), np.float64(0.474), np.float64(0.475), np.float64(0.476), np.float64(0.477), np.float64(0.478), np.float64(0.479), np.float64(0.48), np.float64(0.482), np.float64(0.483), np.float64(0.484), np.float64(0.485), np.float64(0.488), np.float64(0.489), np.float64(0.49), np.float64(0.491), np.float64(0.492), np.float64(0.493), np.float64(0.495), np.float64(0.496), np.float64(0.498), np.float64(0.499), np.float64(0.5), np.float64(0.503), np.float64(0.504), np.float64(0.505), np.float64(0.509), np.float64(0.51), np.float64(0.512), np.float64(0.513), np.float64(0.516), np.float64(0.517), np.float64(0.518), np.float64(0.519), np.float64(0.52), np.float64(0.522), np.float64(0.523), np.float64(0.524), np.float64(0.525), np.float64(0.529), np.float64(0.531), np.float64(0.534), np.float64(0.535), np.float64(0.536), np.float64(0.537), np.float64(0.542), np.float64(0.543), np.float64(0.546), np.float64(0.548), np.float64(0.55), np.float64(0.551), np.float64(0.552), np.float64(0.555), np.float64(0.557), np.float64(0.559), np.float64(0.56), np.float64(0.561), np.float64(0.562), np.float64(0.564), np.float64(0.565), np.float64(0.566), np.float64(0.571), np.float64(0.573), np.float64(0.576), np.float64(0.577), np.float64(0.58), np.float64(0.581), np.float64(0.582), np.float64(0.583), np.float64(0.584), np.float64(0.586), np.float64(0.588), np.float64(0.589), np.float64(0.59), np.float64(0.595), np.float64(0.597), np.float64(0.598), np.float64(0.6), np.float64(0.601), np.float64(0.603), np.float64(0.605), np.float64(0.606), np.float64(0.608), np.float64(0.609), np.float64(0.611), np.float64(0.612), np.float64(0.613), np.float64(0.616), np.float64(0.618), np.float64(0.619), np.float64(0.62), np.float64(0.621), np.float64(0.622), np.float64(0.623), np.float64(0.624), np.float64(0.626), np.float64(0.627), np.float64(0.63), np.float64(0.631), np.float64(0.632), np.float64(0.633), np.float64(0.634), np.float64(0.637), np.float64(0.638), np.float64(0.639), np.float64(0.64), np.float64(0.641), np.float64(0.642), np.float64(0.643), np.float64(0.647), np.float64(0.648), np.float64(0.649), np.float64(0.65), np.float64(0.651), np.float64(0.653), np.float64(0.655), np.float64(0.657), np.float64(0.658), np.float64(0.659), np.float64(0.66), np.float64(0.661), np.float64(0.663), np.float64(0.664), np.float64(0.668), np.float64(0.67), np.float64(0.671), np.float64(0.672), np.float64(0.673), np.float64(0.674), np.float64(0.675), np.float64(0.677), np.float64(0.678), np.float64(0.681), np.float64(0.682), np.float64(0.684), np.float64(0.685), np.float64(0.686), np.float64(0.687), np.float64(0.688), np.float64(0.689), np.float64(0.69), np.float64(0.691), np.float64(0.692), np.float64(0.693), np.float64(0.694), np.float64(0.695), np.float64(0.696), np.float64(0.698), np.float64(0.7), np.float64(0.702), np.float64(0.704), np.float64(0.705), np.float64(0.71), np.float64(0.715), np.float64(0.716), np.float64(0.717), np.float64(0.718), np.float64(0.72), np.float64(0.722), np.float64(0.724), np.float64(0.727), np.float64(0.731), np.float64(0.733), np.float64(0.735), np.float64(0.737), np.float64(0.738), np.float64(0.739), np.float64(0.741), np.float64(0.746), np.float64(0.748), np.float64(0.749), np.float64(0.753), np.float64(0.754), np.float64(0.758), np.float64(0.764), np.float64(0.767), np.float64(0.768), np.float64(0.781), np.float64(0.782), np.float64(0.783), np.float64(0.793), np.float64(0.796), np.float64(0.801), np.float64(0.805), np.float64(0.809), np.float64(0.81), np.float64(0.813), np.float64(0.818), np.float64(0.827), np.float64(0.828), np.float64(0.835), np.float64(0.846)]

In [33]:
print("Interaction difficulty values:")
print(sorted(interactions["difficulty"].unique()))

Interaction difficulty values:
[np.float64(0.152), np.float64(0.153), np.float64(0.156), np.float64(0.158), np.float64(0.171), np.float64(0.185), np.float64(0.193), np.float64(0.199), np.float64(0.2), np.float64(0.202), np.float64(0.205), np.float64(0.206), np.float64(0.207), np.float64(0.209), np.float64(0.21), np.float64(0.213), np.float64(0.216), np.float64(0.219), np.float64(0.22), np.float64(0.221), np.float64(0.223), np.float64(0.224), np.float64(0.226), np.float64(0.227), np.float64(0.229), np.float64(0.235), np.float64(0.241), np.float64(0.246), np.float64(0.249), np.float64(0.254), np.float64(0.255), np.float64(0.258), np.float64(0.261), np.float64(0.262), np.float64(0.263), np.float64(0.264), np.float64(0.265), np.float64(0.268), np.float64(0.269), np.float64(0.27), np.float64(0.273), np.float64(0.282), np.float64(0.283), np.float64(0.285), np.float64(0.287), np.float64(0.288), np.float64(0.29), np.float64(0.294), np.float64(0.297), np.float64(0.299), np.float64(0.301), np.float64(0.307), np.float64(0.309), np.float64(0.31), np.float64(0.311), np.float64(0.313), np.float64(0.318), np.float64(0.319), np.float64(0.322), np.float64(0.323), np.float64(0.324), np.float64(0.326), np.float64(0.33), np.float64(0.333), np.float64(0.334), np.float64(0.335), np.float64(0.336), np.float64(0.337), np.float64(0.338), np.float64(0.339), np.float64(0.341), np.float64(0.343), np.float64(0.344), np.float64(0.346), np.float64(0.348), np.float64(0.354), np.float64(0.355), np.float64(0.356), np.float64(0.357), np.float64(0.359), np.float64(0.36), np.float64(0.361), np.float64(0.363), np.float64(0.364), np.float64(0.366), np.float64(0.367), np.float64(0.37), np.float64(0.371), np.float64(0.373), np.float64(0.374), np.float64(0.376), np.float64(0.377), np.float64(0.378), np.float64(0.38), np.float64(0.381), np.float64(0.382), np.float64(0.384), np.float64(0.385), np.float64(0.387), np.float64(0.388), np.float64(0.39), np.float64(0.391), np.float64(0.392), np.float64(0.393), np.float64(0.397), np.float64(0.4), np.float64(0.401), np.float64(0.402), np.float64(0.403), np.float64(0.405), np.float64(0.406), np.float64(0.407), np.float64(0.408), np.float64(0.411), np.float64(0.414), np.float64(0.415), np.float64(0.416), np.float64(0.417), np.float64(0.419), np.float64(0.42), np.float64(0.421), np.float64(0.422), np.float64(0.424), np.float64(0.425), np.float64(0.426), np.float64(0.43), np.float64(0.431), np.float64(0.433), np.float64(0.435), np.float64(0.436), np.float64(0.438), np.float64(0.44), np.float64(0.442), np.float64(0.443), np.float64(0.445), np.float64(0.446), np.float64(0.447), np.float64(0.448), np.float64(0.449), np.float64(0.451), np.float64(0.452), np.float64(0.454), np.float64(0.455), np.float64(0.457), np.float64(0.458), np.float64(0.46), np.float64(0.462), np.float64(0.464), np.float64(0.465), np.float64(0.466), np.float64(0.469), np.float64(0.47), np.float64(0.471), np.float64(0.472), np.float64(0.473), np.float64(0.474), np.float64(0.475), np.float64(0.476), np.float64(0.477), np.float64(0.478), np.float64(0.479), np.float64(0.48), np.float64(0.482), np.float64(0.483), np.float64(0.484), np.float64(0.485), np.float64(0.488), np.float64(0.489), np.float64(0.49), np.float64(0.491), np.float64(0.492), np.float64(0.493), np.float64(0.495), np.float64(0.496), np.float64(0.498), np.float64(0.499), np.float64(0.5), np.float64(0.503), np.float64(0.504), np.float64(0.505), np.float64(0.509), np.float64(0.51), np.float64(0.512), np.float64(0.513), np.float64(0.516), np.float64(0.517), np.float64(0.518), np.float64(0.519), np.float64(0.52), np.float64(0.522), np.float64(0.523), np.float64(0.524), np.float64(0.525), np.float64(0.529), np.float64(0.531), np.float64(0.534), np.float64(0.535), np.float64(0.536), np.float64(0.537), np.float64(0.542), np.float64(0.543), np.float64(0.546), np.float64(0.548), np.float64(0.55), np.float64(0.551), np.float64(0.552), np.float64(0.555), np.float64(0.557), np.float64(0.559), np.float64(0.56), np.float64(0.561), np.float64(0.562), np.float64(0.564), np.float64(0.565), np.float64(0.566), np.float64(0.571), np.float64(0.573), np.float64(0.576), np.float64(0.577), np.float64(0.58), np.float64(0.581), np.float64(0.582), np.float64(0.583), np.float64(0.584), np.float64(0.586), np.float64(0.588), np.float64(0.589), np.float64(0.59), np.float64(0.595), np.float64(0.597), np.float64(0.598), np.float64(0.6), np.float64(0.601), np.float64(0.603), np.float64(0.605), np.float64(0.606), np.float64(0.608), np.float64(0.609), np.float64(0.611), np.float64(0.612), np.float64(0.613), np.float64(0.616), np.float64(0.618), np.float64(0.619), np.float64(0.62), np.float64(0.621), np.float64(0.622), np.float64(0.623), np.float64(0.624), np.float64(0.626), np.float64(0.627), np.float64(0.63), np.float64(0.631), np.float64(0.632), np.float64(0.633), np.float64(0.634), np.float64(0.637), np.float64(0.638), np.float64(0.639), np.float64(0.64), np.float64(0.641), np.float64(0.642), np.float64(0.643), np.float64(0.647), np.float64(0.648), np.float64(0.649), np.float64(0.65), np.float64(0.651), np.float64(0.653), np.float64(0.655), np.float64(0.657), np.float64(0.658), np.float64(0.659), np.float64(0.66), np.float64(0.661), np.float64(0.663), np.float64(0.664), np.float64(0.668), np.float64(0.67), np.float64(0.671), np.float64(0.672), np.float64(0.673), np.float64(0.674), np.float64(0.675), np.float64(0.677), np.float64(0.678), np.float64(0.681), np.float64(0.682), np.float64(0.684), np.float64(0.685), np.float64(0.686), np.float64(0.687), np.float64(0.688), np.float64(0.689), np.float64(0.69), np.float64(0.691), np.float64(0.692), np.float64(0.693), np.float64(0.694), np.float64(0.695), np.float64(0.696), np.float64(0.698), np.float64(0.7), np.float64(0.702), np.float64(0.704), np.float64(0.705), np.float64(0.71), np.float64(0.715), np.float64(0.716), np.float64(0.717), np.float64(0.718), np.float64(0.72), np.float64(0.722), np.float64(0.724), np.float64(0.727), np.float64(0.731), np.float64(0.733), np.float64(0.735), np.float64(0.737), np.float64(0.738), np.float64(0.739), np.float64(0.741), np.float64(0.746), np.float64(0.748), np.float64(0.749), np.float64(0.753), np.float64(0.754), np.float64(0.758), np.float64(0.764), np.float64(0.767), np.float64(0.768), np.float64(0.781), np.float64(0.782), np.float64(0.783), np.float64(0.793), np.float64(0.796), np.float64(0.801), np.float64(0.805), np.float64(0.809), np.float64(0.81), np.float64(0.813), np.float64(0.818), np.float64(0.827), np.float64(0.828), np.float64(0.835), np.float64(0.846)]

In [34]:
student_ability = (
    interactions
    .groupby("student_id")
    .agg(
        total_attempts=("correct", "count"),
        overall_accuracy=("correct", "mean")
    )
    .reset_index()
)

student_ability.head()

  student_id  total_attempts  overall_accuracy
0       S001             100              0.29
1       S002             100              0.34
2       S003             100              0.25
3       S004             100              0.18
4       S005             100              0.25

## 5.18 — Decide the appropriate difficulty

In [35]:
def choose_difficulty(accuracy, difficulty_values):
    
    difficulty_values = sorted(difficulty_values)
    
    if len(difficulty_values) == 1:
        return difficulty_values[0]
    
    if accuracy < 0.50:
        return difficulty_values[0]
    
    elif accuracy < 0.75:
        return difficulty_values[len(difficulty_values) // 2]
    
    else:
        return difficulty_values[-1]

In [36]:
difficulty_values = sorted(
    questions["difficulty"].unique()
)

print("Available difficulties:", difficulty_values)

print("Accuracy 0.40:",
      choose_difficulty(0.40, difficulty_values))

print("Accuracy 0.65:",
      choose_difficulty(0.65, difficulty_values))

print("Accuracy 0.85:",
      choose_difficulty(0.85, difficulty_values))

Available difficulties: [np.float64(0.152), np.float64(0.153), np.float64(0.156), np.float64(0.158), np.float64(0.171), np.float64(0.185), np.float64(0.193), np.float64(0.199), np.float64(0.2), np.float64(0.202), np.float64(0.205), np.float64(0.206), np.float64(0.207), np.float64(0.209), np.float64(0.21), np.float64(0.213), np.float64(0.216), np.float64(0.219), np.float64(0.22), np.float64(0.221), np.float64(0.223), np.float64(0.224), np.float64(0.226), np.float64(0.227), np.float64(0.229), np.float64(0.235), np.float64(0.241), np.float64(0.246), np.float64(0.249), np.float64(0.254), np.float64(0.255), np.float64(0.258), np.float64(0.261), np.float64(0.262), np.float64(0.263), np.float64(0.264), np.float64(0.265), np.float64(0.268), np.float64(0.269), np.float64(0.27), np.float64(0.273), np.float64(0.282), np.float64(0.283), np.float64(0.285), np.float64(0.287), np.float64(0.288), np.float64(0.29), np.float64(0.294), np.float64(0.297), np.float64(0.299), np.float64(0.301), np.float64(0.307), np.float64(0.309), np.float64(0.31), np.float64(0.311), np.float64(0.313), np.float64(0.318), np.float64(0.319), np.float64(0.322), np.float64(0.323), np.float64(0.324), np.float64(0.326), np.float64(0.33), np.float64(0.333), np.float64(0.334), np.float64(0.335), np.float64(0.336), np.float64(0.337), np.float64(0.338), np.float64(0.339), np.float64(0.341), np.float64(0.343), np.float64(0.344), np.float64(0.346), np.float64(0.348), np.float64(0.354), np.float64(0.355), np.float64(0.356), np.float64(0.357), np.float64(0.359), np.float64(0.36), np.float64(0.361), np.float64(0.363), np.float64(0.364), np.float64(0.366), np.float64(0.367), np.float64(0.37), np.float64(0.371), np.float64(0.373), np.float64(0.374), np.float64(0.376), np.float64(0.377), np.float64(0.378), np.float64(0.38), np.float64(0.381), np.float64(0.382), np.float64(0.384), np.float64(0.385), np.float64(0.387), np.float64(0.388), np.float64(0.39), np.float64(0.391), np.float64(0.392), np.float64(0.393), np.float64(0.397), np.float64(0.4), np.float64(0.401), np.float64(0.402), np.float64(0.403), np.float64(0.405), np.float64(0.406), np.float64(0.407), np.float64(0.408), np.float64(0.411), np.float64(0.414), np.float64(0.415), np.float64(0.416), np.float64(0.417), np.float64(0.419), np.float64(0.42), np.float64(0.421), np.float64(0.422), np.float64(0.424), np.float64(0.425), np.float64(0.426), np.float64(0.43), np.float64(0.431), np.float64(0.433), np.float64(0.435), np.float64(0.436), np.float64(0.438), np.float64(0.44), np.float64(0.442), np.float64(0.443), np.float64(0.445), np.float64(0.446), np.float64(0.447), np.float64(0.448), np.float64(0.449), np.float64(0.451), np.float64(0.452), np.float64(0.454), np.float64(0.455), np.float64(0.457), np.float64(0.458), np.float64(0.46), np.float64(0.462), np.float64(0.464), np.float64(0.465), np.float64(0.466), np.float64(0.469), np.float64(0.47), np.float64(0.471), np.float64(0.472), np.float64(0.473), np.float64(0.474), np.float64(0.475), np.float64(0.476), np.float64(0.477), np.float64(0.478), np.float64(0.479), np.float64(0.48), np.float64(0.482), np.float64(0.483), np.float64(0.484), np.float64(0.485), np.float64(0.488), np.float64(0.489), np.float64(0.49), np.float64(0.491), np.float64(0.492), np.float64(0.493), np.float64(0.495), np.float64(0.496), np.float64(0.498), np.float64(0.499), np.float64(0.5), np.float64(0.503), np.float64(0.504), np.float64(0.505), np.float64(0.509), np.float64(0.51), np.float64(0.512), np.float64(0.513), np.float64(0.516), np.float64(0.517), np.float64(0.518), np.float64(0.519), np.float64(0.52), np.float64(0.522), np.float64(0.523), np.float64(0.524), np.float64(0.525), np.float64(0.529), np.float64(0.531), np.float64(0.534), np.float64(0.535), np.float64(0.536), np.float64(0.537), np.float64(0.542), np.float64(0.543), np.float64(0.546), np.float64(0.548), np.float64(0.55), np.float64(0.551), np.float64(0.552), np.float64(0.555), np.float64(0.557), np.float64(0.559), np.float64(0.56), np.float64(0.561), np.float64(0.562), np.float64(0.564), np.float64(0.565), np.float64(0.566), np.float64(0.571), np.float64(0.573), np.float64(0.576), np.float64(0.577), np.float64(0.58), np.float64(0.581), np.float64(0.582), np.float64(0.583), np.float64(0.584), np.float64(0.586), np.float64(0.588), np.float64(0.589), np.float64(0.59), np.float64(0.595), np.float64(0.597), np.float64(0.598), np.float64(0.6), np.float64(0.601), np.float64(0.603), np.float64(0.605), np.float64(0.606), np.float64(0.608), np.float64(0.609), np.float64(0.611), np.float64(0.612), np.float64(0.613), np.float64(0.616), np.float64(0.618), np.float64(0.619), np.float64(0.62), np.float64(0.621), np.float64(0.622), np.float64(0.623), np.float64(0.624), np.float64(0.626), np.float64(0.627), np.float64(0.63), np.float64(0.631), np.float64(0.632), np.float64(0.633), np.float64(0.634), np.float64(0.637), np.float64(0.638), np.float64(0.639), np.float64(0.64), np.float64(0.641), np.float64(0.642), np.float64(0.643), np.float64(0.647), np.float64(0.648), np.float64(0.649), np.float64(0.65), np.float64(0.651), np.float64(0.653), np.float64(0.655), np.float64(0.657), np.float64(0.658), np.float64(0.659), np.float64(0.66), np.float64(0.661), np.float64(0.663), np.float64(0.664), np.float64(0.668), np.float64(0.67), np.float64(0.671), np.float64(0.672), np.float64(0.673), np.float64(0.674), np.float64(0.675), np.float64(0.677), np.float64(0.678), np.float64(0.681), np.float64(0.682), np.float64(0.684), np.float64(0.685), np.float64(0.686), np.float64(0.687), np.float64(0.688), np.float64(0.689), np.float64(0.69), np.float64(0.691), np.float64(0.692), np.float64(0.693), np.float64(0.694), np.float64(0.695), np.float64(0.696), np.float64(0.698), np.float64(0.7), np.float64(0.702), np.float64(0.704), np.float64(0.705), np.float64(0.71), np.float64(0.715), np.float64(0.716), np.float64(0.717), np.float64(0.718), np.float64(0.72), np.float64(0.722), np.float64(0.724), np.float64(0.727), np.float64(0.731), np.float64(0.733), np.float64(0.735), np.float64(0.737), np.float64(0.738), np.float64(0.739), np.float64(0.741), np.float64(0.746), np.float64(0.748), np.float64(0.749), np.float64(0.753), np.float64(0.754), np.float64(0.758), np.float64(0.764), np.float64(0.767), np.float64(0.768), np.float64(0.781), np.float64(0.782), np.float64(0.783), np.float64(0.793), np.float64(0.796), np.float64(0.801), np.float64(0.805), np.float64(0.809), np.float64(0.81), np.float64(0.813), np.float64(0.818), np.float64(0.827), np.float64(0.828), np.float64(0.835), np.float64(0.846)]
Accuracy 0.40: 0.152
Accuracy 0.65: 0.496
Accuracy 0.85: 0.846

Weak student
    ↓
Easier question

Medium student
    ↓
Medium question

Strong student
    ↓
Harder question

## 5.19 — Create a smart recommendation function

In [38]:
def recommend_smart_questions(
    student_id,
    num_questions=5
):
    
    # -----------------------------
    # 1. Get student's profile
    # -----------------------------
    
    student_profile = student_concept_profile[
        student_concept_profile["student_id"] == student_id
    ].copy()
    
    if student_profile.empty:
        print("Student not found.")
        return pd.DataFrame()
    
    
    # -----------------------------
    # 2. Get student's ability
    # -----------------------------
    
    ability_row = student_ability[
        student_ability["student_id"] == student_id
    ]
    
    if ability_row.empty:
        print("Student ability not found.")
        return pd.DataFrame()
    
    student_accuracy = (
        ability_row["overall_accuracy"].iloc[0]
    )
    
    
    # -----------------------------
    # 3. Find highest priority concept
    # -----------------------------
    
    student_profile = student_profile.sort_values(
        "priority_score",
        ascending=False
    )
    
    target_concept = (
        student_profile.iloc[0]["concept"]
    )
    
    concept_accuracy = (
        student_profile.iloc[0]["accuracy"]
    )
    
    forgetting_risk = (
        student_profile.iloc[0]
        ["forgetting_probability"]
    )
    
    
    # -----------------------------
    # 4. Choose suitable difficulty
    # -----------------------------
    
    target_difficulty = choose_difficulty(
        student_accuracy,
        difficulty_values
    )
    
    
    # -----------------------------
    # 5. Get questions for concept
    # -----------------------------
    
    candidates = questions[
        questions["concept"] == target_concept
    ].copy()
    
    
    # -----------------------------
    # 6. Remove already attempted
    # -----------------------------
    
    attempted = interactions[
        interactions["student_id"] == student_id
    ]["question_id"].unique()
    
    candidates = candidates[
        ~candidates["question_id"].isin(attempted)
    ].copy()
    
    
    if candidates.empty:
        print(
            "No unattempted questions available "
            "for this concept."
        )
        return pd.DataFrame()
    
    
    # -----------------------------
    # 7. Calculate difficulty match
    # -----------------------------
    
    candidates["difficulty_match"] = (
        1 -
        abs(
            candidates["difficulty"]
            - target_difficulty
        )
        /
        max(
            difficulty_values[-1]
            - difficulty_values[0],
            1
        )
    )
    
    
    # -----------------------------
    # 8. Recommendation score
    # -----------------------------
    
    candidates["concept_priority"] = (
        0.6 * (1 - concept_accuracy)
        +
        0.4 * forgetting_risk
    )
    
    candidates["recommendation_score"] = (
        0.60 * candidates["concept_priority"]
        +
        0.40 * candidates["difficulty_match"]
    )
    
    
    # -----------------------------
    # 9. Rank questions
    # -----------------------------
    
    candidates = candidates.sort_values(
        "recommendation_score",
        ascending=False
    )
    
    
    # -----------------------------
    # 10. Return top questions
    # -----------------------------
    
    return candidates.head(num_questions)

## 5.20 — Test the smart recommender

In [39]:
test_student = interactions[
    "student_id"
].iloc[0]

print("Testing student:", test_student)

Testing student: S001

In [40]:
recommended = recommend_smart_questions(
    test_student,
    num_questions=5
)

recommended

,question_id,concept,difficulty,difficulty_match,concept_priority,recommendation_score
263,Q264,TRANSACTIONS,0.523,0.629,0.986301,0.843381
253,Q254,TRANSACTIONS,0.536,0.616,0.986301,0.838181
137,Q138,TRANSACTIONS,0.588,0.564,0.986301,0.817381
66,Q067,TRANSACTIONS,0.606,0.546,0.986301,0.810181
432,Q433,TRANSACTIONS,0.619,0.533,0.986301,0.804981

In [41]:
if not recommended.empty:
    
    display_columns = [
        "question_id",
        "concept",
        "difficulty",
        "recommendation_score"
    ]
    
    print(
        f"\nRecommended questions for {test_student}:"
    )
    
    display(
        recommended[display_columns]
    )

Recommended questions for S001:

    question_id       concept  difficulty  recommendation_score
263        Q264  TRANSACTIONS       0.523              0.843381
253        Q254  TRANSACTIONS       0.536              0.838181
137        Q138  TRANSACTIONS       0.588              0.817381
66         Q067  TRANSACTIONS       0.606              0.810181
432        Q433  TRANSACTIONS       0.619              0.804981

## 5.22 — Show WHY the questions were recommended

In [43]:
# Get the selected student's profile
student_profile = student_concept_profile[
    student_concept_profile["student_id"] == test_student
].sort_values(
    "priority_score",
    ascending=False
)

# Check that profile exists
if student_profile.empty:
    print("No profile found for this student.")

else:
    # Get highest priority concept
    top_concept = student_profile.iloc[0]

    # Get student's overall accuracy
    ability_row = student_ability[
        student_ability["student_id"] == test_student
    ]

    student_accuracy = (
        ability_row["overall_accuracy"].iloc[0]
    )

    # Choose suitable difficulty
    target_difficulty = choose_difficulty(
        student_accuracy,
        difficulty_values
    )

    print("========== RECOMMENDATION REASON ==========")

    print("Student:",
          test_student)

    print(
        "Target concept:",
        top_concept["concept"]
    )

    print(
        "Concept accuracy:",
        round(
            top_concept["accuracy"],
            3
        )
    )

    print(
        "Forgetting probability:",
        round(
            top_concept["forgetting_probability"],
            3
        )
    )

    print(
        "Priority score:",
        round(
            top_concept["priority_score"],
            3
        )
    )

    print(
        "Student overall accuracy:",
        round(
            student_accuracy,
            3
        )
    )

    print(
        "Recommended difficulty:",
        target_difficulty
    )

========== RECOMMENDATION REASON ==========
Student: S001
Target concept: TRANSACTIONS
Concept accuracy: 0.0
Forgetting probability: 0.966
Priority score: 0.986
Student overall accuracy: 0.29
Recommended difficulty: 0.152

In [44]:
test_students = interactions[
    "student_id"
].unique()[:10]

for student in test_students:
    
    recommendation = recommend_smart_questions(
        student,
        num_questions=3
    )
    
    print("\n" + "=" * 50)
    print("Student:", student)
    
    if recommendation.empty:
        print("No recommendations available.")
    else:
        print(
            recommendation[
                [
                    "question_id",
                    "concept",
                    "difficulty",
                    "recommendation_score"
                ]
            ].to_string(index=False)
        )

==================================================
Student: S001
question_id      concept  difficulty  recommendation_score
       Q264 TRANSACTIONS       0.523              0.843381
       Q254 TRANSACTIONS       0.536              0.838181
       Q138 TRANSACTIONS       0.588              0.817381

==================================================
Student: S002
question_id  concept  difficulty  recommendation_score
       Q375 TRIGGERS       0.555              0.831099
       Q054 TRIGGERS       0.559              0.829499
       Q332 TRIGGERS       0.562              0.828299

==================================================
Student: S003
question_id concept  difficulty  recommendation_score
       Q010   UNION       0.357              0.910441
       Q271   UNION       0.382              0.900441
       Q387   UNION       0.384              0.899641

==================================================
Student: S004
question_id  concept  difficulty  recommendation_score
       Q092 GROUP BY       0.355              0.891346
       Q189 GROUP BY       0.364              0.887746
       Q084 GROUP BY       0.374              0.883746

==================================================
Student: S005
question_id concept  difficulty  recommendation_score
       Q008   JOINS       0.400              0.895986
       Q335   JOINS       0.436              0.881586
       Q083   JOINS       0.473              0.866786

==================================================
Student: S006
question_id  concept  difficulty  recommendation_score
       Q154 INDEXING       0.465              0.840995
       Q122 INDEXING       0.478              0.835795
       Q112 INDEXING       0.480              0.834995

==================================================
Student: S007
question_id    concept  difficulty  recommendation_score
       Q017 INNER JOIN       0.354               0.91134
       Q163 INNER JOIN       0.376               0.90254
       Q358 INNER JOIN       0.377               0.90214

==================================================
Student: S008
question_id  concept  difficulty  recommendation_score
       Q092 GROUP BY       0.355              0.881917
       Q189 GROUP BY       0.364              0.878317
       Q084 GROUP BY       0.374              0.874317

==================================================
Student: S009
question_id concept  difficulty  recommendation_score
       Q010   UNION       0.357              0.904221
       Q271   UNION       0.382              0.894221
       Q394   UNION       0.411              0.882621

==================================================
Student: S010
question_id           concept  difficulty  recommendation_score
       Q274 STORED PROCEDURES       0.630              0.800971
       Q480 STORED PROCEDURES       0.638              0.797771
       Q392 STORED PROCEDURES       0.686              0.778571

## 5.24 — Create recommendations for ALL students

In [45]:
all_recommendations = []

for student in interactions["student_id"].unique():
    
    recommendations = recommend_smart_questions(
        student,
        num_questions=5
    )
    
    if not recommendations.empty:
        
        recommendations = recommendations.copy()
        
        recommendations["student_id"] = student
        
        all_recommendations.append(
            recommendations
        )

In [46]:
all_recommendations = pd.concat(
    all_recommendations,
    ignore_index=True
)

print(
    "Total recommendations:",
    len(all_recommendations)
)

Total recommendations: 500

## 5.25 — Arrange the final output

In [47]:
final_recommendations = all_recommendations[
    [
        "student_id",
        "question_id",
        "concept",
        "difficulty",
        "concept_priority",
        "difficulty_match",
        "recommendation_score"
    ]
].sort_values(
    [
        "student_id",
        "recommendation_score"
    ],
    ascending=[True, False]
)

final_recommendations.head(20)

,student_id,question_id,concept,difficulty,concept_priority,difficulty_match,recommendation_score
0,S001,Q264,TRANSACTIONS,0.523,0.986301,0.629,0.843381
1,S001,Q254,TRANSACTIONS,0.536,0.986301,0.616,0.838181
2,S001,Q138,TRANSACTIONS,0.588,0.986301,0.564,0.817381
3,S001,Q067,TRANSACTIONS,0.606,0.986301,0.546,0.810181
4,S001,Q433,TRANSACTIONS,0.619,0.986301,0.533,0.804981
5,S002,Q375,TRIGGERS,0.555,0.987166,0.597,0.831099
6,S002,Q054,TRIGGERS,0.559,0.987166,0.593,0.829499
7,S002,Q332,TRIGGERS,0.562,0.987166,0.590,0.828299
8,S002,Q251,TRIGGERS,0.583,0.987166,0.569,0.819899
9,S002,Q060,TRIGGERS,0.598,0.987166,0.554,0.813899
10,S003,Q010,UNION,0.357,0.987401,0.795,0.910441
11,S003,Q271,UNION,0.382,0.987401,0.770,0.900441
12,S003,Q387,UNION,0.384,0.987401,0.768,0.899641
13,S003,Q394,UNION,0.411,0.987401,0.741,0.888841
14,S003,Q359,UNION,0.420,0.987401,0.732,0.885241
15,S004,Q092,GROUP BY,0.355,0.954243,0.797,0.891346
16,S004,Q189,GROUP BY,0.364,0.954243,0.788,0.887746
17,S004,Q084,GROUP BY,0.374,0.954243,0.778,0.883746
18,S004,Q005,GROUP BY,0.393,0.954243,0.759,0.876146
19,S004,Q186,GROUP BY,0.402,0.954243,0.750,0.872546

## 5.26 — Save the recommendations

In [49]:
final_recommendations.to_csv(
    "learntwin_question_recommendations.csv",
    index=False
)

print(
    "Question recommendations saved successfully!"
)

Question recommendations saved successfully!

## 5.27 — Save the updated recommendation notebook model information

In [50]:
student_concept_profile.to_csv(
    "learntwin_student_concept_profile.csv",
    index=False
)

print(
    "Student concept profiles saved successfully!"
)

Student concept profiles saved successfully!

## 05_question_recommendation.ipynb
   ##     │
  #      ├── Weak concept detection       ✅
   #     ├── Forgetting risk              ✅
  #      ├── Student ability              ✅
  #      ├── Difficulty adaptation        ✅
  #      ├── Recommendation scoring       ✅
  #      ├── Remove attempted questions   ✅
  #      ├── Rank questions               ✅
  #      ├── Explain recommendation       ✅
  #      └── Save recommendations         ✅